fileGroups:
  phpSources:
    - "./*.php"
    - "src/**/*.php"
  phpTests:
    - "tests/**/*.php"

tasks:
  format:
    command:
      - "$workspaceRoot/vendor/bin/php-cs-fixer"
      - "fix"
      - "."
    inputs:
      - "@group(phpSources)"
      - "@group(phpTests)"

  lint:
    command:
      - "$workspaceRoot/vendor/bin/phpstan"
    inputs:
      - "@group(phpSources)"
      - "@group(phpTests)"
      - "phpstan.dist.neon" # Invalidate task cache on config change
    deps:
      - "lintComposerJson"
      - "format"

  test:
    command: "vendor/bin/pest"
    inputs:
      - "@group(phpSources)"
      - "@group(phpTests)"

  dev:
    command: "composer dev"
